"""create_inventory_optimization_domain_schema

Revision ID: 816603e8f43e
Revises: '0001_initial_schema'
Create Date: 2026-09-16 02:42:53.485817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816603e8f43e'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_centers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_centers_code'), 'distribution_centers', ['code'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('pack_size', sa.Integer(), nullable=False),
    sa.Column('unit_weight_lbs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('reliability_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=True)
    op.create_table('daily_demand_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('daily_demand_qty', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('daily_demand_qty >= 0', name='ck_demand_qty_nonneg'),
    sa.ForeignKeyConstraint(['dc_id'], ['distribution_centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dc_id', 'product_id', 'signal_date', name='uq_demand_dc_product_date')
    )
    op.create_index(op.f('ix_daily_demand_signals_dc_id'), 'daily_demand_signals', ['dc_id'], unique=False)
    op.create_index(op.f('ix_daily_demand_signals_product_id'), 'daily_demand_signals', ['product_id'], unique=False)
    op.create_index('ix_demand_signals_dc_product_date', 'daily_demand_signals', ['dc_id', 'product_id', 'signal_date'], unique=False)
    op.create_table('dc_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_dc_id', sa.Integer(), nullable=False),
    sa.Column('target_dc_id', sa.Integer(), nullable=False),
    sa.Column('transit_days', sa.Integer(), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('distance_miles', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cost_per_unit >= 0', name='ck_dc_route_cost_nonneg'),
    sa.CheckConstraint('source_dc_id != target_dc_id', name='ck_dc_route_diff_dcs'),
    sa.CheckConstraint('transit_days >= 1', name='ck_dc_route_transit_days_pos'),
    sa.ForeignKeyConstraint(['source_dc_id'], ['distribution_centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_dc_id'], ['distribution_centers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_dc_id', 'target_dc_id', name='uq_dc_route_source_target')
    )
    op.create_index(op.f('ix_dc_routes_source_dc_id'), 'dc_routes', ['source_dc_id'], unique=False)
    op.create_index('ix_dc_routes_source_target', 'dc_routes', ['source_dc_id', 'target_dc_id'], unique=False)
    op.create_index(op.f('ix_dc_routes_target_dc_id'), 'dc_routes', ['target_dc_id'], unique=False)
    op.create_table('inventory_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('on_hand_qty', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('on_hand_qty >= 0', name='ck_inv_balance_on_hand_nonneg'),
    sa.CheckConstraint('on_hand_qty >= reserved_qty', name='ck_inv_balance_on_hand_ge_reserved'),
    sa.CheckConstraint('reserved_qty >= 0', name='ck_inv_balance_reserved_nonneg'),
    sa.ForeignKeyConstraint(['dc_id'], ['distribution_centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dc_id', 'product_id', name='uq_inventory_balance_dc_product')
    )
    op.create_index(op.f('ix_inventory_balances_dc_id'), 'inventory_balances', ['dc_id'], unique=False)
    op.create_index('ix_inventory_balances_dc_product', 'inventory_balances', ['dc_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_inventory_balances_product_id'), 'inventory_balances', ['product_id'], unique=False)
    op.create_table('inventory_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('safety_stock_days', sa.Float(), nullable=False),
    sa.Column('min_reorder_qty', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('min_reorder_qty >= 0', name='ck_inv_policy_min_reorder_nonneg'),
    sa.CheckConstraint('safety_stock_days >= 0', name='ck_inv_policy_safety_days_nonneg'),
    sa.ForeignKeyConstraint(['dc_id'], ['distribution_centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dc_id', 'product_id', name='uq_inventory_policy_dc_product')
    )
    op.create_index(op.f('ix_inventory_policies_dc_id'), 'inventory_policies', ['dc_id'], unique=False)
    op.create_index(op.f('ix_inventory_policies_product_id'), 'inventory_policies', ['product_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('destination_dc_id', sa.Integer(), nullable=False),
    sa.Column('ordered_qty', sa.Integer(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('ordered_qty > 0', name='ck_po_ordered_qty_pos'),
    sa.ForeignKeyConstraint(['destination_dc_id'], ['distribution_centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_destination_dc_id'), 'purchase_orders', ['destination_dc_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_product_id'), 'purchase_orders', ['product_id'], unique=False)
    op.create_index('ix_purchase_orders_supplier_dc_status', 'purchase_orders', ['supplier_id', 'destination_dc_id', 'status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('risk_incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_code', sa.String(length=100), nullable=False),
    sa.Column('target_dc_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('current_dos', sa.Float(), nullable=False),
    sa.Column('days_to_stockout', sa.Float(), nullable=False),
    sa.Column('projected_stockout_date', sa.Date(), nullable=False),
    sa.Column('shortage_qty', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_dc_id'], ['distribution_centers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_incidents_incident_code'), 'risk_incidents', ['incident_code'], unique=True)
    op.create_index(op.f('ix_risk_incidents_product_id'), 'risk_incidents', ['product_id'], unique=False)
    op.create_index(op.f('ix_risk_incidents_target_dc_id'), 'risk_incidents', ['target_dc_id'], unique=False)
    op.create_index('ix_risk_incidents_target_prod_status_sev', 'risk_incidents', ['target_dc_id', 'product_id', 'status', 'severity'], unique=False)
    op.create_table('supplier_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_sku', sa.String(length=100), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('std_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('min_order_qty', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('min_order_qty > 0', name='ck_supplier_product_min_qty_pos'),
    sa.CheckConstraint('std_lead_time_days >= 0', name='ck_supplier_product_lead_time_nonneg'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_supplier_product_cost_nonneg'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'product_id', name='uq_supplier_product')
    )
    op.create_index(op.f('ix_supplier_products_product_id'), 'supplier_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_products_supplier_id'), 'supplier_products', ['supplier_id'], unique=False)
    op.create_table('supply_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('disrupted_qty', sa.Integer(), nullable=False),
    sa.Column('new_expected_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('delay_days >= 0', name='ck_supply_event_delay_nonneg'),
    sa.CheckConstraint('disrupted_qty >= 0', name='ck_supply_event_disrupted_nonneg'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_events_po_id'), 'supply_events', ['po_id'], unique=False)
    op.create_table('transfer_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_code', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('source_dc_id', sa.Integer(), nullable=False),
    sa.Column('target_dc_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('recommended_qty', sa.Integer(), nullable=False),
    sa.Column('feasible_qty_snapshot', sa.Integer(), nullable=False),
    sa.Column('source_surplus_snapshot', sa.Integer(), nullable=False),
    sa.Column('transit_days_snapshot', sa.Integer(), nullable=False),
    sa.Column('route_unit_cost_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_cost_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('recommendation_source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('recommended_qty > 0', name='ck_rec_qty_pos'),
    sa.CheckConstraint('source_dc_id != target_dc_id', name='ck_rec_diff_dcs'),
    sa.ForeignKeyConstraint(['incident_id'], ['risk_incidents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_dc_id'], ['distribution_centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_dc_id'], ['distribution_centers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_recommendations_incident_id'), 'transfer_recommendations', ['incident_id'], unique=False)
    op.create_index('ix_transfer_recommendations_incident_source', 'transfer_recommendations', ['incident_id', 'source_dc_id'], unique=False)
    op.create_index(op.f('ix_transfer_recommendations_product_id'), 'transfer_recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_transfer_recommendations_recommendation_code'), 'transfer_recommendations', ['recommendation_code'], unique=True)
    op.create_index(op.f('ix_transfer_recommendations_source_dc_id'), 'transfer_recommendations', ['source_dc_id'], unique=False)
    op.create_index(op.f('ix_transfer_recommendations_target_dc_id'), 'transfer_recommendations', ['target_dc_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('planner_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('input_snapshot_json', sa.Text(), nullable=True),
    sa.Column('final_approved_qty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['risk_incidents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['transfer_recommendations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_incident_id'), 'audit_events', ['incident_id'], unique=False)
    op.create_index('ix_audit_events_incident_rec_created', 'audit_events', ['incident_id', 'recommendation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_recommendation_id'), 'audit_events', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_recommendation_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_incident_rec_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_incident_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_transfer_recommendations_target_dc_id'), table_name='transfer_recommendations')
    op.drop_index(op.f('ix_transfer_recommendations_source_dc_id'), table_name='transfer_recommendations')
    op.drop_index(op.f('ix_transfer_recommendations_recommendation_code'), table_name='transfer_recommendations')
    op.drop_index(op.f('ix_transfer_recommendations_product_id'), table_name='transfer_recommendations')
    op.drop_index('ix_transfer_recommendations_incident_source', table_name='transfer_recommendations')
    op.drop_index(op.f('ix_transfer_recommendations_incident_id'), table_name='transfer_recommendations')
    op.drop_table('transfer_recommendations')
    op.drop_index(op.f('ix_supply_events_po_id'), table_name='supply_events')
    op.drop_table('supply_events')
    op.drop_index(op.f('ix_supplier_products_supplier_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_product_id'), table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index('ix_risk_incidents_target_prod_status_sev', table_name='risk_incidents')
    op.drop_index(op.f('ix_risk_incidents_target_dc_id'), table_name='risk_incidents')
    op.drop_index(op.f('ix_risk_incidents_product_id'), table_name='risk_incidents')
    op.drop_index(op.f('ix_risk_incidents_incident_code'), table_name='risk_incidents')
    op.drop_table('risk_incidents')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_supplier_dc_status', table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_product_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_destination_dc_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_inventory_policies_product_id'), table_name='inventory_policies')
    op.drop_index(op.f('ix_inventory_policies_dc_id'), table_name='inventory_policies')
    op.drop_table('inventory_policies')
    op.drop_index(op.f('ix_inventory_balances_product_id'), table_name='inventory_balances')
    op.drop_index('ix_inventory_balances_dc_product', table_name='inventory_balances')
    op.drop_index(op.f('ix_inventory_balances_dc_id'), table_name='inventory_balances')
    op.drop_table('inventory_balances')
    op.drop_index(op.f('ix_dc_routes_target_dc_id'), table_name='dc_routes')
    op.drop_index('ix_dc_routes_source_target', table_name='dc_routes')
    op.drop_index(op.f('ix_dc_routes_source_dc_id'), table_name='dc_routes')
    op.drop_table('dc_routes')
    op.drop_index('ix_demand_signals_dc_product_date', table_name='daily_demand_signals')
    op.drop_index(op.f('ix_daily_demand_signals_product_id'), table_name='daily_demand_signals')
    op.drop_index(op.f('ix_daily_demand_signals_dc_id'), table_name='daily_demand_signals')
    op.drop_table('daily_demand_signals')
    op.drop_index(op.f('ix_suppliers_supplier_code'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_distribution_centers_code'), table_name='distribution_centers')
    op.drop_table('distribution_centers')
    # ### end Alembic commands ###
